language: python
matrix:
  include:
    - os: osx
      language: generic
      sudo: required
    - os: linux
      python: 3.2
      sudo: required
    - os: windows
      language: sh
      python: "3.6"
      before_install:
        - choco install python3
        - export PATH="/c/Python36:/c/Python36/Scripts:$PATH"

install:
  - pip install -r requirements.txt

script:
  - ./build.sh
  - ls

deploy:
  provider: releases
  api_key: $GITHUB_OATU_TOKEN
  local_dir: "dist"
  skip_cleanup: true
  on:
    branches: true
