language: python
os:
  - osx
  - windows
  - linux
python:
  - "3.5"

install:
  - pip install -r requirements.txt

script:
  - pyinstaller -F main.py

deploy:
  provider: releases
  api_key: $GITHUB_OATU_TOKEN
  file: "dist"
  skip_cleanup: true
  on:
    branches: true
