language: python
matrix:
  include:
    - os: osx
      language: generic
      env: TOXENV=py33
    - os: linux
      python: 3.2
      env: TOXENV=py32

install:
  - pip install -r requirements.txt

script:
  - pyinstaller -F main.py

deploy:
  provider: releases
  api_key: $GITHUB_OATU_TOKEN
  file: "dist"
  skip_cleanup: true
  on:
    branches: true
