language: python

install:
  - pip3 install -r requirements.txt

script:
  - chmod +x build.sh
  - ./build.sh
  - ls -R

jobs:
  include:
    - stage: build macOS binary
      os: osx
      language: generic
      sudo: required
      if: tag IS present
      before_deploy:
        - tar -cvf dist/CNKI-Converter-macOS.app.tar dist/CNKI-Converter-darwin.app
        - python3 deploy_to_cos.py
      deploy:
        provider: releases
        api_key: $GITHUB_OATU_TOKEN
        file:
          - dist/**/*.tar
          - dist/**/*.json
        file_glob: true
        skip_cleanup: true
        on:
          branch: master
          tags: true

    - stage: build Windows binary
      os: windows
      language: sh
      if: tag IS present
      before_install:
        - choco install python --version=3.7.4
        - export PATH="/c/Python37:/c/Python37/Scripts:$PATH"
      before_deploy:
        - python3 deploy_to_cos.py
      deploy:
        provider: releases
        api_key: $GITHUB_OATU_TOKEN
        file:
          - dist/**/*.exe
          - dist/**/*.json
        file_glob: true
        skip_cleanup: true
        on:
          branch: master
          tags: true
